import Layout from "../../components/layout"
import Link from 'next/link'
import utilStyles from '../../styles/utils.module.css'

export default function Posts() {
    return (
        <Layout>
            <h2 className={utilStyles.headingXl}>Poking the system</h2>
            <h3 className={utilStyles.headingLg}>I.</h3>
            <p>Reading has a lifespan.  Reading ingredients on a packaging is not the same as reading a thousand page novel.  One is <em>bigger</em> than the other.  There is a notion of physicality and it is associated with all kinds of things — including time.  What takes less time feels small.  What takes more time seems big.  A decade feels physically bigger than a second to me.</p>
            <p>Like reading, all activities work on timescales — in the form of a task or in the form of a project.  Tasks live for a short time.  They tend to be simpler and easier.  Projects live longer.  They are built of ambition and novelty.  Like reading, all activities have an attached physicality.  Tasks are small and projects are big.</p>
            <p><em>Smallness</em> is easy to understand.  My brain is efficient at processing small chunks of time.  I know, in my gut, what it feels like to pay attention for minutes or hours.  How four is different from fourteen.  I can feel the size of a room, and how many people can fit in it.  How many people can a continent fit?  <em>Bigness</em> is fuzzy.  Things become indistinguishable beyond a certain size.  Paying attention for a year feels no different than paying attention for a decade.  A billion isn't that different from a trillion, is it?  They seem different but feel the same.</p>
            <p>~</p>
            <p>Polarity strengthens with time and the perception scale of physicality keeps on shifting.  Small things become smaller.  Big things become bigger.  Minutes become the new hour and months blend into decades.  Simple becomes boring and challenging becomes scary.  Details are lost and the bigness becomes fuzzier.  Things are moving at an incomprehensible pace.  I blame the rampant expansion of our universe.</p>
            <p>The affinity to simplicity has always persisted.  It is easier to watch a thirty second video than to sit for hours with a documentary; easier to write fifty words than to write fifty thousand words; and easier to draw for an hour than to fill a canvas with months.  Fleeting things ask for little effort and attention.  They can only respond with a fleeting joy.  The mirror can only reflect as much as it takes.</p>
            <p>It would be a waste of a civilization if nobody pushed beyond the fleetingness.</p>
            <p>Humans have the privilege of cognition and can afford an honest attempt at understanding the bigness.  Those who can have a duty that they must.  The pursuit of a project is a worthy goal in itself.  Projects carry prestige, tasks do not.  The challenge of a project is enticing.  A challenge evokes the sense of flow.  It reveals the richness of the hidden parts.</p>
            <p>The arduous challenge of a project is bigger than tasks.  It is also harder to realize.  A project can feel too distant, devoid of any details, and boring.  It can feel immeasurable, overwhelming, and scary.  The obscurity surrounding meaningful endeavors — that projects are — pushes people away towards the simplicity of tasks.</p>
            <p>I wish to work on meaningful endeavors that span multiple years.</p>
            <p>~</p>

            <h3 className={utilStyles.headingLg}>II.</h3>
            <p>Tasks and projects have a relation to them.  Small pieces hide in the fuzziness of big pieces.  Reality has a <Link href="http://johnsalvatier.org/blog/2017/reality-has-a-surprising-amount-of-detail"><a target="_blank">surprising</a></Link> amount of detail.  Details like to hide as relations.  The relation between tasks and projects is not very hard to see.  Tasks integrate to a project.  Project disintegrates into tasks.  This knowledge, however simple, is non-trivial.</p>
            <p>In a colloquial sense of the words 'science' and 'art', disintegration is like a science and integration is like an art.  Moving from the abstract to concrete in one and moving from the concrete to abstract in another.  Analyzing in one and synthesizing in another.</p>
            <p>The ability to analyze a problem well is widely recognized, highly desired, and handsomely rewarded.  It is natural that we value breaking big and complex things down to small and simple things.  Atoms don't have problems, humans do.  Problems exist only in higher dimensions.  They only grow in the fertility of sufficient complexity.  We know well how to <em>solve</em> them.  With the hammer of first principles we can break big monsters into hundred tiny monsters.  This simple idea sparked the industrial revolution and is the default way to make problems go away today.  First principles thinking is the darling of all corporations.</p>
            <p>This top-down relation is how we relate projects and tasks best.  A project can be broken down into simpler tasks.  But there is a certain lifelessness to this relation.  Death is the precursor to decomposition; you must kill in order to analyze.  Breaking things down to simple bits as the only approach becomes joyless inconspicuously fast.</p>
            <p>A cluster of cells becomes life at some point.  Synthesis gives rise to emergent properties.  With sufficient order, life emerges from nothingness.  Atoms turn into people, people turn into families, families turn into communities, communities turn into towns, towns turn into cities, cities turn into countries.   It is a mysterious process — akin to magic.  It is tough to tame.  Small pieces tangle together in secret ways to create the big.</p>
            <p>Tasks can integrate into projects.  The bottom-up relation between tasks and projects is harder to see with foresight.  Emergence is not deterministic enough.   Betting on emergence makes for a bad business principle — What if the parts integrate poorly to be less than the sum?</p>
            <p>Things with little utilitarian value wither away from common knowledge.</p>
            <p>~</p>
            <p>Over-reliance on analysis makes things dull.  The top-down view is too predictable and feels stagnant.  Leaning too heavy on synthesis can be chaotic.  The bottom-up view is too unpredictable and impractical.  What is lacking in one is the strength of the other.</p>
            <p>Analysis and synthesis are two sides of the same coin.  They do not exist in isolation.  They co-exist and they co-evolve.  Analysis demystifies synthesis and synthesis strengthens analysis.</p>
            <p>There is a rhythm of cyclicality to most things.  Tasks, projects, analysis and synthesis form an ecosystem that is in constant motion.  Cultivating an understanding of the interplay of these components is a critical part of making the concept of a project comprehensible.  A project requires a fine iterative balance.  To balance well is to <em>design</em> well.</p>
            <p>~</p>

            <h3 className={utilStyles.headingLg}>III.</h3>
            <p><Link href="https://www.benkuhn.net/thinkrealhard/" ><a target="_blank">Thinking hard</a></Link> is a difficult thing.  It feels cumbersome and unpleasant.  To avoid this unpleasantness and to make our lives convenient and pleasant we have delegated a lot of thinking to the outside.  There is a constant push, disguised in the name of efficiency, to reduce the default operating context of a human brain.  We might as well happily believe that food is made inside of a computer in the pursuit of simplification.  Unpleasant things like thinking are a grave threat to humanity.</p>
            <p>Humans invented computing in an attempt to automate the boring and hard.  It was a means to augment the human capability.  Computers are much more than an augmentation today.  An aid left unchecked for too long can become a crutch.  It can give way to atrophy of the attention muscles.</p>
            <p>The relational cyclicality becomes harder to see without the capacity to think hard.  When small becomes smaller and big become bigger then the threads that tie the small and the big together stretch too thin.  The ability to perceive connecting threads breaks apart.  A reinforcing pattern sets in.  The more things move apart, the harder it becomes to see the connections.  The harder it becomes to see the connections, the more things move apart.  The worlds grow further apart over time and they lose their interconnectedness.  To me this is more unpleasant than thinking hard.</p>
            <p>There is a problem of diminishing understanding of the web of relations.</p>
            <p>One component of the solution is asking the right question.  The solution to a problem follows its good articulation.  Answers often lie in the questions.  If you seek connections, they will reveal themselves.  The other component of the solution is to <Link href="https://www.benkuhn.net/listen/"><a target="_blank">listen well</a></Link>.  When you ask and when you listen, then you learn about the design.</p>
            <p>~</p>
            <p>There was a time when we did not have a global shortage of trees.  There was enough of nature to teach us about the systems and their interconnections.  If we take a cue from the remains we can see synthesis in play.  Nature reveals its design.  And it teaches how to design a design.  To design is to realize, move between and thread together the different layers.  Nature makes it abundantly clear that the process of design is iterative.</p>
            <p>Nature does not create beings inconsistent with its laws.</p>
            <p>A forest is like a project.  The rules of design apply as much to a decade long project as they apply to a forest.  There is no recipe or playbook to build a forest.  However there is one critical component.  You cannot build a forest without the awareness of its ecology.  This awareness also happens to be a sufficient condition to tend to a forest.  In the same way, an understanding of the web of interconnectedness is a critical component of making projects comprehensible.  To work on a project is to continuously create and refine a design.</p>
            <p>The best way to reason about the fuzziness of a grand prospect is to ask a question to yourself.  Part of the fun lies in learning how to dance in the dark.  You are going to play the game of life anyway, why not learn the controls better?  Perhaps the exercise of writing about systems at length can help.</p>
            <p>To design is to do and to do is to design.  Poke the systems and let them poke you back.</p>
            <p>~</p>
        </Layout>
    )
}